version: '3'
services:
  web:
    container_name: web
    restart: always
    build:
      context: .
    ports:
      - '3000:3000'

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
